import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Home from '../../components/place-to-go/Home'

export default function Place() {
    const router = useRouter()
    const { id } = router.query
    return (
      <>
        <Head>
          <title>Free Tours Argentina</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />

          <link rel="icon" href="" />
        </Head>
        <main className={styles.main}>
            <Home placeName={'Bariloche'} description={'La ciudad de la nieve'}/>
        </main>
      </>
    )
  }
  