import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from '../../styles/Places.module.css'
import Home from '../../components/place-to-go/Home'
import About from '../../components/place-to-go/About'
import Gallery from '../../components/place-to-go/Gallery'
import Map from '../../components/place-to-go/Map'
import Footer from '../../components/Footer'
import Contact from '../../components/place-to-go/Contact'
import ContactButton from '../../components/pure/place-to-go/ContactButton'
import { useInView } from 'react-intersection-observer'

export default function Place() {
    const router = useRouter()
    const { id } = router.query
    const { ref: footerRef, inView: footerVisible } = useInView()
    const { ref: gridRef, inView: gridVisible } = useInView()
    return (
      <>
        <Head>
          <title>Free Tours Argentina</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />

          <link rel="icon" href="" />
        </Head>
        <main className={styles.main}>
            <Home placeName={'Bariloche'} description={'La ciudad de la nieve'}/>
            <About refValue={gridRef} gridVisible={gridVisible}/>
            <Gallery/>
            <Map/>
            <Contact/>
            <Footer refValue={footerRef}/>
            <ContactButton footerVisible={footerVisible}/>
        </main>
      </>
    )
  }
  