import React, { useRef } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import BlogCardLarger from '../../components/blog/BlogCardLarger'
import BlogCard from '../../components/pure/BlogCard'
import Footer from '../../components/Footer'
import { NavBar } from '../../components/NavBar'
import { useRouter } from 'next/router'

export default function Blog() {
    const router = useRouter()
    const footerRef = useRef()
    return(
        <>
            <Head>
            <title>Free Tours Argentina | Blog</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/assets/logoMundo.png" />
            </Head>
            <NavBar action={() => {router.back()}} type={'blog'}/>
            <main className={styles.main}>
                <div style={{marginTop: '60px'}}>
                    <div className='titleSection' id={'about'} style={{ marginTop: '2rem' }}>
                        <h2>FREE TOUR ARGENTINA</h2>
                        <h1>NUESTRO BLOG</h1>
                        <hr/>
                    </div>
                </div>
                <div className={styles.BlogContainer}>
                    <BlogCardLarger image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'}/>
                    <div className={styles.Blog}>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                    </div>
                    <BlogCardLarger image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'}/>
                    <div className={styles.Blog}>
                    <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                        <BlogCard image={'/assets/blogExample/1.jpg'} title={'-2°C En Bariloche!!'} subtitle={'Llegó el invierno a nuestra ciudad'} date={'19 dic 22'} tourName={''} tourLogo={''}/>
                    </div>
                </div>
                <Footer refValue={footerRef}/>
            </main>
        </>
    )
}