import React from 'react'
import Head from 'next/head'
import styles from '../../styles/Places.module.css'
import Home from '../../components/place-to-go/Home'
import About from '../../components/place-to-go/About'
import Gallery from '../../components/place-to-go/Gallery'
import Map from '../../components/place-to-go/Map'
import Footer from '../../components/Footer'
import Contact from '../../components/place-to-go/Contact'
import ContactButton from '../../components/pure/place-to-go/ContactButton'
import { useInView } from 'react-intersection-observer'
import { NavBar } from '../../components/NavBar'
import Comments from '../../components/place-to-go/Comments'
import { getTour } from '../../services/tours/getTour'
import router from 'next/router'
import { ITour } from '../../models/Tour'

export default function Place({tour}: {tour: ITour}) {
    // eslint-disable-next-line no-unused-vars
    const { ref: footerRef, inView: footerVisible } = useInView()
    return (
      <>
        <Head>
          <title>Free Tours Argentina</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/assets/logoMundo.png" />
        </Head>
        <NavBar action={() => {router.back()}} type={'place'}/>
        <main className={styles.main}>
            <Home placeName={tour.name} description={tour.shortDescription}/>
            <About tour={tour}/>
            <Gallery/>
            <Map/>
            <Contact/>
            <Comments/>
            <Footer refValue={footerRef}/>
            <ContactButton footerVisible={footerVisible}/>
        </main>
      </>
    )
  }
  export async function getStaticPaths() {
    return {
        paths: [],
        fallback: 'blocking'
    }
  }
  export async function getStaticProps(context: any) {
    const tour = await getTour(context.params.id)
    return {
      props: {tour}, 
    }
  }